# Generated by Django 4.2.3 on 2023-08-07 05:54

from django.db import migrations, models
import django.db.models.deletion
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_name'),
        ('product', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products', validators=[product.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', validators=[product.validators.validate_category]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[product.validators.validate_description]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[product.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[product.validators.validate_price]),
        ),
    ]
