# Generated by Django 4.2.3 on 2023-08-07 05:54

import category.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[category.validators.validate_name, category.validators.validate_description]),
        ),
    ]
